# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b092d49981591f043b20005b910111f5eb5cb7a4ad1b730d14d0c66224f5bccfafb6a491e24c2a1cf629412102cfca1d540bd1eaaaca5d5f75a6c76e01493f2

test:
  secret_key_base: 0373471bd639ac92911d6ae41308db8d80f32f68fee571b55384b992e0b5dc14777174acdb1015996ec1123b145ecddb4b946eb825c7ae3d59553e1dda2cdf23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
